lookahead_distance : 0.50 #one bakma mesafesi
speed : 0.8 #maksimum hiz
expansion_size : 3 #duvar genisletme katsayisi
target_error : 0.15 #hedefe olan hata payi
robot_r : 0.956 #lokal guvenlik icin robot mesafesi